version: "3"
services:
  db:
    image: postgresql:latest
    restart: always
    environment:
      POSTGRES_DB: 'mentalhealth'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/workdir
    ports:
      - "8000:8000"
#    depends_on:
#      - db
# Names our volume
volumes:
  db:
