"""migration

Revision ID: d1ff62c73e78
Revises: d662bb89477b
Create Date: 2023-05-07 14:07:40.717645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ff62c73e78'
down_revision = 'd662bb89477b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
