"""migration

Revision ID: e56e5e7cfb3d
Revises: 6f653857e0c0
Create Date: 2023-05-07 13:21:22.431514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e56e5e7cfb3d'
down_revision = '6f653857e0c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index('ix_chat_status', table_name='chat')
    op.drop_column('chat', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('status', mysql.VARCHAR(length=32), nullable=False))
    op.create_index('ix_chat_status', 'chat', ['status'], unique=False)
    op.drop_column('chat', 'is_active')
    # ### end Alembic commands ###
